// Post and Comment Templates for Bot System

export const POST_TEMPLATES = {
  tech: [
    'Descobri que X é muito melhor que Y. Alguém já testou?',
    'Finalmente implementei [feature] e os resultados foram incríveis 🚀',
    'Pro tip: use [tool] para [result]. Mudou meu workflow completamente',
    'Alguém mais enfrenta esse problema com [problem]? Como vocês resolvem?',
    'Tutorial: como fazer [task] em 5 minutos ⏱️',
    'Comparei 5 ferramentas e [tool] venceu por isso tudo',
    'Acabei de descobrir um bug em [project]. Alguém sabe o workaround?',
    '[Lang] vs [Lang]: qual vocês preferem? 🤔',
    'Open source ftw! Contribuir em [project] foi incrível',
    'Palestra sobre [topic] ontem foi reveladora. Recomendo!',
  ],
  lifestyle: [
    'Sexta à noite tem que ser assim! 🎉',
    'Encontrei o melhor lugar para [activity] na cidade',
    'Estou viciado em [hobby]. Alguém mais?',
    'Que dia lindo! 🌞',
    'Novo projeto saiu do forno. Que acham?',
    'Finalmente consegui [achievement]. Que emoção!',
    'Alguém mais ama [thing] tanto quanto eu?',
    'Dica: [tip]. Sua vida vai mudar 💡',
    'Os finais de semana são meu escape 🏝️',
    'Que emoção! Mal posso acreditar que consegui!',
  ],
  business: [
    'Fechamos uma parceria importante com [company] 🎊',
    'Novo produto lançado! Confira o link',
    'Atingimos [number] clientes esse mês. Muito grato!',
    'Compartilhando insights sobre [topic]',
    'Growing our team! Estamos contratando em [role]',
    'Dica de negócio: sempre [advice]',
    'Qual é o maior desafio que vocês enfrentam em [area]?',
    'Estou otimista sobre o futuro de [market]',
    'Aprendizado do dia: [lesson]',
    'Não é fácil, mas vale cada segundo do esforço 💪',
  ],
  questions: [
    'Qual é a melhor maneira de fazer [task]?',
    'Vocês já tiveram problema com [issue]?',
    'Recomendações para [thing]?',
    'Qual ferramenta vocês usam para [task]?',
    'Alguém sabe como [question]?',
    'Dúvida: [doubt]. Como vocês fazem?',
    '[Thing] realmente compensa?',
    'Qual é o melhor [option]?',
  ],
  inspiration: [
    'O sucesso é uma jornada, não um destino 🚀',
    'Tudo é possível quando você acredita 💪',
    'Falhas são apenas redirecionamentos para o sucesso',
    'Seu limite é sua imaginação 🧠',
    'Nunca é tarde para começar algo novo',
    'A consistência é a chave do sucesso 🔑',
    'Sonhe grande, trabalhe duro, realize mais',
    'A melhor hora foi ontem. A segunda melhor é agora',
  ],
};

export const COMMENT_TEMPLATES = {
  tech: [
    'Ótima observação! Também percebi isso',
    'Concordo 100%. Também tive essa experiência',
    'Legal! Vou testar com certeza',
    'Sabia não! Muito útil mesmo',
    'Tem tutorial sobre isso?',
    'Qualidade demais! Obrigado por compartilhar',
    'Como você fez exatamente esse passo?',
    'Excelente conteúdo! Salvando aqui',
    'Será que funciona com [version]?',
    'Faz sentido. Vou aplicar isso no meu projeto',
  ],
  agreement: [
    'Concordo demais!',
    'Exato!',
    '100% verdade',
    'Muito bom mesmo',
    'Perfeito!',
    'Isso aí!',
    'Precisávamos ouvir isso',
    'Fato absoluto',
    'Muito sábio',
    'Top demais',
  ],
  question: [
    'Como assim?',
    'Mais detalhes sobre isso?',
    'Você pode elaborar?',
    'Qual é a sua fonte?',
    'Você tem um link?',
    'Como chegou a essa conclusão?',
    'Pode compartilhar exemplos?',
    'Quando isso começou?',
    'Qual foi o resultado?',
  ],
  encouragement: [
    'Parabéns! Muito legal!',
    'Que legal! Muito bom mesmo',
    'Incrível! Adorei',
    'Que top! 🎉',
    'Sensacional!',
    'Fantástico!',
    'Que sucesso!',
    'Muito melhor do que esperava',
  ],
};

export const HASHTAGS = [
  '#tech', '#startup', '#business', '#inovação', '#código',
  '#programação', '#desenvolvimento', '#design', '#produto',
  '#marketing', '#empreendedorismo', '#comunidade', '#viralizar',
  '#dia', '#motivação', '#trending', '#novo', '#incrível',
  '#dica', '#importante', '#imperdível', '#atenção', '#confira',
];

export const INTERESTS = [
  'tecnologia', 'programação', 'design', 'marketing', 'negócios',
  'empreendedorismo', 'startups', 'inovação', 'fotografia', 'viagens',
  'lifestyle', 'fitness', 'educação', 'gaming', 'música',
  'arte', 'cinema', 'literatura', 'moda', 'gastronomia',
];
